(()=>{
const SUPA='https://lzzicjintgeqzsetmzhk.supabase.co';
const PUB='sb_publishable_D3_CVQIDpo_wHkPA5q7z4g_rI3tZoRo';
const SPACE_KEY='ourSchedule.cloud.activeSpace.v1';
let rows=[];
function auth(){for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(/^sb-.*-auth-token$/.test(k)){try{const x=JSON.parse(localStorage.getItem(k)||'null');if(x?.access_token)return x}catch{}}}return null}
function fmt(t){try{return new Intl.DateTimeFormat('zh-TW',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Taipei'}).format(new Date(t))}catch{return t||''}}
function verb(a){return a==='added'?'新增':a==='deleted'?'刪除':'編輯'}
function css(){if(document.getElementById('histStyle'))return;const s=document.createElement('style');s.id='histStyle';s.textContent=`.history-btn{border:1px solid var(--line);background:#fff;border-radius:999px;padding:8px 12px;color:var(--ink)}.history-meta{font-size:11px;color:var(--muted);margin-top:7px}.history-modal{display:none;position:fixed;inset:0;z-index:80;background:#0005;align-items:flex-end;justify-content:center}.history-modal.open{display:flex}.history-sheet{width:min(680px,100%);max-height:88vh;overflow:auto;background:#fffaf9;border-radius:24px 24px 0 0;padding:18px}.history-list{display:grid;gap:9px}.history-row{border:1px solid var(--line);background:#fff;border-radius:16px;padding:12px}.history-row b{display:block;margin-bottom:4px}.history-sub{font-size:12px;color:var(--muted);line-height:1.5}`;document.head.appendChild(s)}
async function load(){const a=auth(),space=localStorage.getItem(SPACE_KEY);if(!a||!space)return;const url=`${SUPA}/rest/v1/schedule_edit_history?space_id=eq.${encodeURIComponent(space)}&select=id,event_id,action,event_name,event_date,editor_name,edited_at&order=edited_at.desc&limit=200`;const r=await fetch(url,{headers:{apikey:PUB,Authorization:`Bearer ${a.access_token}`}});if(r.ok){rows=await r.json();decorate()}}
function decorate(){const latest=new Map();for(const r of rows)if(!latest.has(r.event_name))latest.set(r.event_name,r);document.querySelectorAll('.event-card,.trip-item,.day-list-item').forEach(el=>{if(el.querySelector('.history-meta'))return;const text=(el.querySelector('.event-title,.day-list-name')?.textContent||'').trim();const h=latest.get(text);if(!h)return;const m=document.createElement('div');m.className='history-meta';m.textContent=`最後編輯：${h.editor_name||'對方'}・${fmt(h.edited_at)}`;el.appendChild(m)})}
function modal(){let m=document.getElementById('historyModal');if(m)return m;m=document.createElement('div');m.id='historyModal';m.className='history-modal';m.innerHTML=`<div class="history-sheet"><div class="section-title" style="margin:0 0 12px"><h3>🕘 編輯紀錄</h3><button class="history-btn" id="historyClose">關閉</button></div><div class="history-list" id="historyList"></div></div>`;document.body.appendChild(m);document.getElementById('historyClose').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};return m}
function show(){const m=modal(),list=document.getElementById('historyList');list.innerHTML=rows.length?rows.map(r=>`<div class="history-row"><b>${r.event_name||'行程'}｜${verb(r.action)}</b><div class="history-sub">${r.editor_name||'對方'}・${fmt(r.edited_at)}${r.event_date?`<br>${r.event_date}`:''}</div></div>`).join(''):'<div class="history-sub">目前還沒有編輯紀錄。之後新增、修改、刪除行程都會記錄。</div>';m.classList.add('open')}
function addButton(){const bar=document.querySelector('.cloud-bar-actions');if(!bar||document.getElementById('historyOpen'))return;const b=document.createElement('button');b.id='historyOpen';b.className='cloud-mini-btn';b.type='button';b.textContent='編輯紀錄';b.onclick=show;const manage=document.getElementById('cloudManage');manage?bar.insertBefore(b,manage):bar.appendChild(b)}
function init(){css();addButton();load();new MutationObserver(()=>{addButton();decorate()}).observe(document.body,{subtree:true,childList:true});setInterval(load,60000)}
window.addEventListener('load',()=>setTimeout(init,500),{once:true});
})();