(()=>{
const PHOTO_KEY='ourSchedule.tripPhotos.v1';
const CAPTION_KEY='ourSchedule.photoCaptions.v1';
function parse(k,f){try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}}
function findPath(node,target,path=[]){if(node===target)return path;if(!node||typeof node!=='object')return null;for(const k of Object.keys(node)){const p=findPath(node[k],target,path.concat(k));if(p)return p}return null}
function removePath(obj,path){if(!path||!path.length)return false;let cur=obj;for(let i=0;i<path.length-1;i++){if(!cur||typeof cur!=='object')return false;cur=cur[path[i]]}if(cur&&Object.prototype.hasOwnProperty.call(cur,path[path.length-1])){if(Array.isArray(cur))cur.splice(Number(path[path.length-1]),1);else delete cur[path[path.length-1]];return true}return false}
function cleanEmpty(obj){if(!obj||typeof obj!=='object')return;for(const k of Object.keys(obj)){const v=obj[k];if(v&&typeof v==='object'){cleanEmpty(v);if((Array.isArray(v)&&v.length===0)||(!Array.isArray(v)&&Object.keys(v).length===0))delete obj[k]}}}
function candidateKeys(item){const out=[];for(const el of item.querySelectorAll('[data-id],[data-event-id],input[id],label[for]')){for(const v of [el.dataset?.id,el.dataset?.eventId,el.id,el.getAttribute?.('for')])if(v)out.push(String(v).replace(/^photo[-_]?/i,''))}return [...new Set(out.filter(Boolean))]}
function removeByCandidates(obj,keys){for(const k of keys){if(Object.prototype.hasOwnProperty.call(obj,k)){delete obj[k];return true}for(const p of Object.keys(obj)){if(obj[p]&&typeof obj[p]==='object'&&Object.prototype.hasOwnProperty.call(obj[p],k)){delete obj[p][k];return true}}}return false}
function decorate(){document.querySelectorAll('.trip-item').forEach(item=>{const img=item.querySelector('.photo-box img');if(!img||item.querySelector('.trip-photo-delete'))return;const add=item.querySelector('.trip-photo-btn');const b=document.createElement('button');b.type='button';b.className='trip-photo-delete';b.textContent='🗑️ 刪除照片';b.style.cssText='display:block;width:100%;margin-top:8px;border:1px solid #f0cfd3;background:#fff7f7;color:#b24b55;border-radius:999px;padding:8px 12px';b.onclick=()=>{if(!confirm('確定要刪除這張照片嗎？'))return;const photos=parse(PHOTO_KEY,{}),caps=parse(CAPTION_KEY,{}),src=img.currentSrc||img.src;let path=findPath(photos,src);let removed=removePath(photos,path);const keys=candidateKeys(item);if(!removed)removed=removeByCandidates(photos,keys);if(path)removePath(caps,path);removeByCandidates(caps,keys);cleanEmpty(photos);cleanEmpty(caps);if(!removed){alert('找不到這張照片的儲存資料，請重新整理後再試。');return}localStorage.setItem(PHOTO_KEY,JSON.stringify(photos));localStorage.setItem(CAPTION_KEY,JSON.stringify(caps));window.dispatchEvent(new CustomEvent('ourschedule:cloud-data'));item.querySelector('.photo-box').innerHTML='尚未加入照片';b.remove();setTimeout(decorate,100)};add?add.insertAdjacentElement('afterend',b):img.closest('.photo-box')?.insertAdjacentElement('afterend',b)})}
const mo=new MutationObserver(()=>decorate());window.addEventListener('load',()=>{decorate();mo.observe(document.body,{childList:true,subtree:true})},{once:true});
})();